name: CI with Email Notification

on:
  push:
    branches: [main]
  pull_requests:
    branches:[main]
  workflow_run:
    workflows : ["CI with Email Notification"]
    types:
      - completed

jobs:
  build: 
    runs-on : ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run script
        run : |
          echo"This will fails"
          exit 1 # Force failure for testing testing

notify_on_failure:
  if: failure() 
  needs: build
  runs-on: ubuntu-latest
  steps:
  - name: Send email on failure
    uses: dawidd6/action-send-mail@v3
    with:
      server_address: smtp.example.com
      server_port: 587
      username: ${{ secrets.SMTP_USERNAME }}
      password: ${{ secrets.SMTP_PASSWORD }}
      subject: GitHub Actions CI Failed 🚨
      to: info@bibekbhandari.com.np
      from: github-actions@example.com
      body: |
        CI job failed on repository ${{ github.repository }}.
        Commit: ${{ github.sha }}
        Workflow: ${{ github.workflow }}
        Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}